### ISSUE TITLE
[Enhancement] Saving password of polarion in seperate JSON file

### ISSUE THREAD

**Issue by fabianbally** [jesper-raemaekers/vscode-polarion#1]
When using this extension in a production-like environment with git, you don't want to push your Polarion password, too. On the other hand, you will very likely want to have your vscode settings in your repos for contributors to use it. 

The most practical solution I could think of is to save username and password in an own separate file. When pushing a commit, you then can explicitly exclude this file from the commits with gitignore.

I really like what you are doing here. It makes working with Polarion a lot easier for developers. Keep up the great work!

**Comment by jesper-raemaekers** [comment]
Thanks for the feedback and I agree that it would be best to store the login details in a separate file.

**Comment by jesper-raemaekers** [comment]
This change has been released in 0.2.2. 

I'm happy to receive more feedback if you have more ideas.
